apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.84.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  values:
