apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - onepassworditem.yaml
configMapGenerator:
  - name: tailscale-helm-values
    namespace: tailscale
    files:
      - values.yaml=helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true
