apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: damianwasik98@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - http01:
          ingress:
            class: traefik
