apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-user-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Ti
  volumeName: nextcloud
  storageClassName: manual
