apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - onepassworditem.yaml
configMapGenerator:
  - name: nextcloud-helm-values
    namespace: nextcloud
    files:
      - values.yaml=helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true
