apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 10m
  chart:
    spec:
      chart: homepage
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: homepage-helm-values

