apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: homepage-helm-values
    namespace: homepage
    files:
      - values.yaml=helm-values.yaml
generatorOptions:
  disableNameSuffixHash: true

