apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: connect
  namespace: 1password-connect
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: 1password-connect
  values:
    connect:
      credentialsName: "1password-connect-credentials"
      credentailsKey: "1password-credentials.json"
